### ISSUE TITLE
Larger format poster?

### ISSUE THREAD

**Issue by vessenes** [eleanorlutz/asteroids_atlas_of_space#5]
Hi Eleanor, I love this, and would be interested in a large format (maybe 60"x60") version of the poster - any interest in selling a print of that size? I would imagine you'd want to rerasterize the illustrator file into something big; I couldn't find poster links of that size online anywhere.

**Comment by eleanorlutz** [comment]
Hi Peter, I'm really glad to hear you liked this map! Unfortunately I don't have any 60x60 posters, because the production company I work with doesn't sell posters of that size. And it does take a fair amount of time to re-generate the image and redesign the font sizes for a larger format, so it's probably not something I'll be able to offer anytime soon.
